config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations], controllers: {
    sessions:      'users/sessions'
    # registrations: 'users/registrations'
  }
 
  devise_scope :user do
    put 'users' => 'users/registrations#update', as: 'registration'
    get 'users/edit' => 'users/registrations#edit', as: 'edit_user_registration'
    delete 'users' => 'users/registrations#destroy', as: 'remove_registration'
  end

  namespace :admin do
    resources :coupons
    resources :products
    resources :categories

    put '/category_popular/:id' => 'categories#category_popular', as: :category_popular
    put '/product_special/:id'  => 'products#product_special', as: :product_special
    put '/product_home_page/:id'  => 'products#product_home_page', as: :product_home_page
  end

  
  get 'menu'       => 'menu#index'
  get 'admin'      => 'admin/products#index'
  # root to: 'home#index'
  root to: 'under_construction#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :category_popular]
  
  def category_popular
    @category.update_attributes!(home_page: params[:category])
    render :nothing => true, :status => 200, :content_type => 'text/html'
  end

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for ([:admin, category]), html:{class: 'form-horizontal form-label-left'} do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="item form-group">
    <%= f.label :title, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Title: <span class="required">*</span>
    <% end %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :title, class: 'form-control col-md-7 col-xs-12', placeholder: "Title", required: "required"%>
    </div>
  </div>

  <div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-md-offset-3">
      <%= link_to "Cancel", admin_categories_path, class: 'btn btn-primary' %>
      <%= f.submit class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h1>Edit Category <small></small></h2>
        <ul class="nav navbar-left panel_toolbox">
          <li> <%= link_to 'Back', admin_categories_path, class: 'btn btn-default btn-lg' %> </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
		<%= render 'form', category: @category %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<h1 class='center'>Categories</h1>

<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <ul class="nav navbar-right panel_toolbox">
        <%= link_to "Add Category", new_admin_category_path, class: 'btn btn-primary' %>
      </ul>
      <div class="clearfix"></div>
    </div>

    <div class="x_content">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Title</th>
            <th>Popular(makes vision in main page)</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <th scope="row"> <%= category.id %> </th>
              <td><%= category.title %></td>
              <td>
                <%= check_box_tag('category[:home_page]', '', checked = category.home_page, id: "category_popular_#{category.id}" )%>

                <script>
                     $("#category_popular_<%= category.id %>").change(function(){
                      var check_box_value = ( $("#category_popular_<%= category.id %>").is(':checked') ) ? true : false;
                       $.ajax({
                            url: '<%= admin_category_popular_path(category) %>',
                            type: 'PUT',
                            data: {category: check_box_value },
                            success: function(data, textStatus, jqXHR) {
                            var alert_status = (check_box_value) ? 'in popular list.' : 'Removed from popular list.';
                              alert("Category: <%= category.title %> " + alert_status);
                            }
                        });
                     })
                </script>
              </td>
              <td>
                  <%= link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-default '%>
                  <%= link_to 'Destroy', admin_category_path(category), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h1>New Category <small></small></h2>
        <ul class="nav navbar-left panel_toolbox">
          <li> <%= link_to 'Back', admin_categories_path, class: 'btn btn-default btn-lg' %> </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
		<%= render 'form', category: @category %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>