config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations], controllers: {
    sessions:      'users/sessions'
    # registrations: 'users/registrations'
  }
 
  devise_scope :user do
    put 'users' => 'users/registrations#update', as: 'registration'
    get 'users/edit' => 'users/registrations#edit', as: 'edit_user_registration'
    delete 'users' => 'users/registrations#destroy', as: 'remove_registration'
  end

  namespace :admin do
    resources :coupons
    resources :products
    resources :categories

    put '/category_popular/:id' => 'categories#category_popular', as: :category_popular
    put '/product_special/:id'  => 'products#product_special', as: :product_special
    put '/product_home_page/:id'  => 'products#product_home_page', as: :product_home_page
  end

  
  get 'menu'       => 'menu#index'
  get 'admin'      => 'admin/products#index'
  # root to: 'home#index'
  root to: 'under_construction#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :product_special, :product_home_page]

  def product_special
    @product.update_attributes!(special: params[:product])
    render :nothing => true, :status => 200, :content_type => 'text/html'
  end

  def product_home_page
    puts "#{params[:product]}"
    @product.update_attributes!(home_page: params[:product])
    render :nothing => true, :status => 200, :content_type => 'text/html'
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_path, success: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :desc, :price, :price, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for ([:admin, product]), html:{class: 'form-horizontal form-label-left'}  do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="item form-group">
    <%= f.label :category_id, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Category Name: <span class="required">*</span>
    <% end %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.collection_select :category_id, Category.all, :id, :title, {prompt: "Choose a category"}, class: 'form-control col-md-7 col-xs-12' %>
    </div>
  </div>

  <div class="item form-group">
    <%= f.label :title, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Title: <span class="required">*</span>
    <% end %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :title, class: 'form-control col-md-7 col-xs-12', placeholder: "Title", required: "required"%>
    </div>
  </div>

  <div class="item form-group">
    <%= f.label :desc, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Description: <span class="required">*</span>
    <% end %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_area :desc, class: 'form-control col-md-7 col-xs-12', required: "required" %>
    </div>
  </div>

  <div class="item form-group">
    <%= f.label :price, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Price: <span class="required">*</span>
    <% end %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :price, class: 'form-control col-md-7 col-xs-12', required: "required" %>
    </div>
  </div>

  <div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-md-offset-3">
      <%= link_to "Cancel", admin_products_path, class: 'btn btn-primary' %>
      <%= f.submit class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h1>Edit Product <small></small></h2>
        <ul class="nav navbar-left panel_toolbox">
          <li> <%= link_to 'Back', admin_products_path, class: 'btn btn-default btn-lg' %> </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
		<%= render 'form', product: @product %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<h1 class='center'>Products</h1>

<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <ul class="nav navbar-right panel_toolbox">
        <%= link_to "Add Product", new_admin_product_path, class: 'btn btn-primary' %>
      </ul>
      <div class="clearfix"></div>
    </div>

    <div class="x_content">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Category</th>
            <th>Title</th>
            <th>Description</th>
            <th>$Price</th>
            <th>Popular(makes vision in main page)</th>
            <th>Special(Special Tag for a product gives GOLD vision)</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <tr>
              <th scope="row"> <%= product.id %> </th>
              <td><%= product.category.title %></td>
              <td><%= product.title %></td>
              <td><%= truncate(product.desc, length: 200) %></td>
              <td>$<%= product.price %></td>
              <td><!-- Popular -->
                <%= check_box_tag('product[:home_page]', '', checked = product.home_page, id: "product_home_page_#{product.id}" )%>
                <script>
                     $("#product_home_page_<%= product.id %>").change(function(){
                      var check_box_value = ( $("#product_home_page_<%= product.id %>").is(':checked') ) ? true : false;
                       $.ajax({
                            url: '<%= admin_product_home_page_path(product) %>',
                            type: 'PUT',
                            data: {product: check_box_value },
                            success: function(data, textStatus, jqXHR) {
                            var alert_status = (check_box_value) ? 'in Home Page list.' : 'Removed from Home Page list.';
                              alert("Product: <%= product.title %> " + alert_status);
                            }
                        });
                     })
                </script>
              </td>
              <td><!-- Special Tag -->
                <%= check_box_tag('product[:special]', '', checked = product.special, id: "product_special_#{product.id}" )%>
                <script>
                     $("#product_special_<%= product.id %>").change(function(){
                      var check_box_value = ( $("#product_special_<%= product.id %>").is(':checked') ) ? true : false;
                       $.ajax({
                            url: '<%= admin_product_special_path(product) %>',
                            type: 'PUT',
                            data: {product: check_box_value },
                            success: function(data, textStatus, jqXHR) {
                            var alert_status = (check_box_value) ? 'in Special list.' : 'Removed from Special list.';
                              alert("Product: <%= product.title %> " + alert_status);
                            }
                        });
                     })
                </script>
              </td>
              <td>
                  <%= link_to 'Edit', edit_admin_product_path(product), class: 'btn btn-default'%>
                  <%= link_to 'Destroy', admin_product_path(product), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h1>New Product <small></small></h2>
        <ul class="nav navbar-left panel_toolbox">
          <li> <%= link_to 'Back', admin_products_path, class: 'btn btn-default btn-lg' %> </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
		<%= render 'form', product: @product %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @product.desc %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>