config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations], controllers: {
    sessions:      'users/sessions'
    # registrations: 'users/registrations'
  }
 
  devise_scope :user do
    put 'users' => 'users/registrations#update', as: 'registration'
    get 'users/edit' => 'users/registrations#edit', as: 'edit_user_registration'
    delete 'users' => 'users/registrations#destroy', as: 'remove_registration'
  end

  namespace :admin do
    resources :coupons
    resources :products
    resources :categories

    put '/category_popular/:id' => 'categories#category_popular', as: :category_popular
    put '/product_special/:id'  => 'products#product_special', as: :product_special
    put '/product_home_page/:id'  => 'products#product_home_page', as: :product_home_page
  end

  
  get 'menu'       => 'menu#index'
  get 'admin'      => 'admin/products#index'
  # root to: 'home#index'
  root to: 'under_construction#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/coupon.rb
class Coupon < ApplicationRecord
end

app/controllers/admin/coupons_controller.rb
class Admin::CouponsController < Admin::AdminController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]

  # GET /coupons
  # GET /coupons.json
  def index
    @coupons = Coupon.all
  end

  # GET /coupons/1
  # GET /coupons/1.json
  def show
  end

  # GET /coupons/new
  def new
    @coupon = Coupon.new
  end

  # GET /coupons/1/edit
  def edit
  end

  # POST /coupons
  # POST /coupons.json
  def create
    @coupon = Coupon.new(coupon_params)

    respond_to do |format|
      if @coupon.save
        format.html { redirect_to admin_coupons_path, notice: 'Coupon was successfully created.' }
        format.json { render :show, status: :created, location: @coupon }
      else
        format.html { render :new }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coupons/1
  # PATCH/PUT /coupons/1.json
  def update
    respond_to do |format|
      if @coupon.update(coupon_params)
        format.html { redirect_to admin_coupons_path, notice: 'Coupon was successfully updated.' }
        format.json { render :show, status: :ok, location: @coupon }
      else
        format.html { render :edit }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1
  # DELETE /coupons/1.json
  def destroy
    @coupon.destroy
    respond_to do |format|
      format.html { redirect_to admin_coupons_path, notice: 'Coupon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coupon_params
      params.require(:coupon).permit(:title, :desc, :price)
    end
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/admin/coupons/_form.html.erb
<%= form_for ([:admin, coupon]), html:{class: 'form-horizontal form-label-left'}  do |f| %>
  <% if coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% coupon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="item form-group">
    <%= f.label :title, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Title: <span class="required">*</span>
    <% end %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :title, class: 'form-control col-md-7 col-xs-12', placeholder: "Title", required: "required"%>
    </div>
  </div>

  <div class="item form-group">
    <%= f.label :desc, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Description: <span class="required">*</span>
    <% end %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_area :desc, class: 'form-control col-md-7 col-xs-12', required: "required" %>
    </div>
  </div>

  <div class="item form-group">
    <%= f.label :price, class: 'control-label col-md-3 col-sm-3 col-xs-12' do %>
      Price: <span class="required">*</span>
    <% end %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :price, class: 'form-control col-md-7 col-xs-12', required: "required" %>
    </div>
  </div>

  <div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-md-offset-3">
      <%= link_to "Cancel", admin_coupons_path, class: 'btn btn-primary' %>
      <%= f.submit class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/admin/coupons/edit.html.erb
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h1>Edit Coupon <small></small></h2>
        <ul class="nav navbar-left panel_toolbox">
          <li> <%= link_to 'Back', admin_coupons_path, class: 'btn btn-default btn-lg' %> </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
		<%= render 'form', coupon: @coupon %>
      </div>
    </div>
  </div>
</div>

app/views/admin/coupons/index.html.erb
<h1 class='center'>Coupons</h1>

<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <ul class="nav navbar-right panel_toolbox">
        <%= link_to "Add Coupon", new_admin_coupon_path, class: 'btn btn-primary' %>
      </ul>
      <div class="clearfix"></div>
    </div>

    <div class="x_content">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Title</th>
            <th>Description</th>
            <th>$Price</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @coupons.each do |c| %>
            <tr>
              <th scope="row"> <%= c.id %> </th>
              <td><%= c.title %></td>
              <td><%= truncate(c.desc, length: 200) %></td>
              <td>$<%= c.price %></td>
              <td>
                  <%= link_to 'Edit', edit_admin_coupon_path(c), class: 'btn btn-default '%>
                  <%= link_to 'Destroy', admin_coupon_path(c), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/coupons/new.html.erb
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h1>New Coupon <small></small></h2>
        <ul class="nav navbar-left panel_toolbox">
          <li> <%= link_to 'Back', admin_coupons_path, class: 'btn btn-default btn-lg' %> </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
		<%= render 'form', coupon: @coupon %>
      </div>
    </div>
  </div>
</div>

app/views/admin/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @coupon.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @coupon.desc %>
</p>

<p>
  <strong>Price:</strong>
  <%= @coupon.price %>
</p>

<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>