config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations], controllers: {
    sessions:      'users/sessions'
    # registrations: 'users/registrations'
  }
 
  devise_scope :user do
    put 'users' => 'users/registrations#update', as: 'registration'
    get 'users/edit' => 'users/registrations#edit', as: 'edit_user_registration'
    delete 'users' => 'users/registrations#destroy', as: 'remove_registration'
  end

  namespace :admin do
    resources :coupons
    resources :products
    resources :categories

    put '/category_popular/:id' => 'categories#category_popular', as: :category_popular
    put '/product_special/:id'  => 'products#product_special', as: :product_special
    put '/product_home_page/:id'  => 'products#product_home_page', as: :product_home_page
  end

  
  get 'menu'       => 'menu#index'
  get 'admin'      => 'admin/products#index'
  # root to: 'home#index'
  root to: 'under_construction#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/coupon.rb
class Coupon < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  mount_uploader :avatar, AvatarUploader
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
	layout 'admin'
	before_action :authenticate_user!
	
end

app/controllers/admin/coupons_controller.rb
class Admin::CouponsController < Admin::AdminController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]

  # GET /coupons
  # GET /coupons.json
  def index
    @coupons = Coupon.all
  end

  # GET /coupons/1
  # GET /coupons/1.json
  def show
  end

  # GET /coupons/new
  def new
    @coupon = Coupon.new
  end

  # GET /coupons/1/edit
  def edit
  end

  # POST /coupons
  # POST /coupons.json
  def create
    @coupon = Coupon.new(coupon_params)

    respond_to do |format|
      if @coupon.save
        format.html { redirect_to admin_coupons_path, notice: 'Coupon was successfully created.' }
        format.json { render :show, status: :created, location: @coupon }
      else
        format.html { render :new }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coupons/1
  # PATCH/PUT /coupons/1.json
  def update
    respond_to do |format|
      if @coupon.update(coupon_params)
        format.html { redirect_to admin_coupons_path, notice: 'Coupon was successfully updated.' }
        format.json { render :show, status: :ok, location: @coupon }
      else
        format.html { render :edit }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1
  # DELETE /coupons/1.json
  def destroy
    @coupon.destroy
    respond_to do |format|
      format.html { redirect_to admin_coupons_path, notice: 'Coupon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coupon_params
      params.require(:coupon).permit(:title, :desc, :price)
    end
end

app/controllers/admin/static_controller.rb
class Admin::StaticController < Admin::AdminController
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

	def index
	end

	def create
	end

	def edit
	end
private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coupon_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  respond_to :html
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@coupons = Coupon.all

	  	# @categories = Category.where(home_page: true).includes(:products)
	  	@categories = Category.where(home_page: true).includes(:products).where("products.home_page = ?", true).references(:products)
		@right = @categories.length / 2
		@left  = @categories.length - @right
	end
	
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  	@categories = Category.includes(:products)
  	@right = @categories.length / 2
  	@left  = @categories.length - @right
  end
end

app/controllers/under_construction_controller.rb
class UnderConstructionController < ApplicationController
  layout "construction"
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def blockk(&block)
	end

	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/under_construction_helper.rb
module UnderConstructionHelper
end

app/views/admin/shared/_footer.html.erb
<footer>
<div class="pull-right">
  @Copyright <a href="https://7urkm3n.github.io">7urkm3n</a>
</div>
<div class="clearfix"></div>
</footer>

app/views/admin/shared/_sidenav.html.erb
<div class="col-md-3 left_col">
  <div class="left_col scroll-view">

    <div class="navbar nav_title" style="border: 0;">
      <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Admin</span></a>
    </div>
    <div class="clearfix"></div>

    <!-- menu prile quick info -->
    <div class="profile">
      <div class="profile_pic">
        <img src="<%= current_user.avatar_url || '/assets/images/img.jpg' %>" alt="..." class="img-circle profile_img">
      </div>
      <div class="profile_info">
        <span>Welcome,</span>
        <h2> <%= "#{current_user.first_name} #{current_user.last_name}" %> </h2>
      </div>
    </div>
    <!-- /menu prile quick info -->

    <br />

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <h3>General</h3>
        <ul class="nav side-menu">
          <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu" style="display: none">
              <li><%= link_to "Dashboard", admin_path %></li>
              <li><%= link_to "Products", admin_products_path %></li>
              <li><%= link_to "Categories", admin_categories_path %></li>
              <li><%= link_to "Coupons", admin_coupons_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
      <%= link_to edit_user_registration_path, title: "Settings", data: { toggle: 'tooltip', placement: 'top' } do %>
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
      <% end %> 

      <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
      </a>

      <%= link_to destroy_user_session_path, title: "Logout", data: { toggle: 'tooltip', placement: 'top' }, :method => :delete do %>
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
      <% end %>

    </div>
    <!-- /menu footer buttons -->
  </div>
</div>

app/views/admin/shared/_topnav.html.erb
<div class="top_nav">

  <div class="nav_menu">
    <nav class="" role="navigation">
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="<%= current_user.avatar_url || '/assets/images/img.jpg' %>" alt=""> <%= "#{current_user.first_name} #{current_user.last_name}"  %>
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li>
              <%= link_to edit_user_registration_path do %>
                <span>Settings</span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, :method => :delete do %>
                Log Out <i class="fa fa-sign-out pull-right"></i>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>

</div>

app/views/shared/_footer.html.erb
<!-- START Site Footer -->
<footer id="site-footer">

	<!-- START Widget Area -->
	<div class="widget-area grid-container">
	
		<!-- START Widget Column 01 -->
		<div class="widget-column widget-column-01 grid-33 tablet-grid-33 mobile-grid-100">
			
			<!-- Contact Details Widget -->
			<aside class="widget widget-hungry-contact-details">
				<h3 class="widget-title">Contact Us</h3>
				<div class="contact-details">
					<p>
						Pizza Three Guys is a full-service Pizzeria located in the Washington, PA. Since opening our doors in 1992, we have provided local families and businesses with delicious, high quality food at affordable prices. All of our rolls and pizzadoughs are baked fresh daily. We use only fresh vegetables that are delivered to all of our locations daily.
					</p>
					<div class="contact-phone">
						<i class="fa fa-phone-square"></i>
						<a class="phone-number-link" href="tel:+00678987658">724-206-0807</a>
					</div>
					<div class="contact-email">
						<i class="fa fa-envelope-square"></i>
						<a class="email-link" href="mailto:bookings@hungrytheme.net">contact@pizzathreeguys.com</a>
					</div>
					<div class="contact-address">
						<i class="fa fa-caret-square-o-down"></i>
						<address>
							374 S Main St, <br />
							Washington, PA 15301
						</address>
					</div>
				</div>
			</aside>

		</div>
		<!-- END Widget Column 01 -->
		
		<!-- START Widget Column 02 -->
		<div class="widget-column widget-column-02 grid-33 tablet-grid-33 mobile-grid-100">
			
			<!-- Latest Recipes Widget -->
			<aside class="widget widget-hungry-latest-recipes">
				<h3 class="widget-title">New on the Menu</h3>
				<ul class="latest-recipes">
					<li class="recipe">
						<a href="template-recipe-single.html"><img class="recipe-thumbnail" src="/assets/demo/widget-recipe-thumbnails/thumbnail-01.jpg" alt="Recipe Thumbnail Image" /></a>
						<h6 class="recipe-title"><a href="template-recipe-single.html">Angus Steak Burger</a></h6>
						<p class="recipe-description">Aenean commodo ligula eget.</p>
					</li>
					<li class="recipe">
						<a href="template-recipe-single.html"><img class="recipe-thumbnail" src="/assets/demo/widget-recipe-thumbnails/thumbnail-02.jpg" alt="Recipe Thumbnail Image" /></a>
						<h6 class="recipe-title"><a href="template-recipe-single.html">Mexican Chicken Fajitas</a></h6>
						<p class="recipe-description">Aenean commodo ligula eget.</p>
					</li>
					<li class="recipe">
						<a href="template-recipe-single.html"><img class="recipe-thumbnail" src="/assets/demo/widget-recipe-thumbnails/thumbnail-03.jpg" alt="Recipe Thumbnail Image" /></a>
						<h6 class="recipe-title"><a href="template-recipe-single.html">Chocolate Fudge Cake</a></h6>
						<p class="recipe-description">Aenean commodo ligula eget.</p>
					</li>
				</ul>
			</aside>
			
		</div>
		<!-- END Widget Column 02 -->
		
		<!-- START Widget Column 03 -->
		<div class="widget-column widget-column-03 grid-33 tablet-grid-33 mobile-grid-100">
			
			<!-- Opening Times Widget -->
			<aside class="widget widget-hungry-opening-times">
				<h3 class="widget-title">Opening Times</h3>
				<ul class="opening-times">
					<li>Monday<span>10am - 11pm</span></li>
					<li>Tuesday<span>10am - 11pm</span></li>
					<li>Wednesday<span>10am - 11pm</span></li>
					<!-- <li>Wednesday<span class="closed">Closed</span></li> -->
					<li>Thursday<span>10am - 11pm</span></li>
					<li>Friday<span>10am - Midnight</span></li>
					<li>Saturday<span>10am - Midnight</span></li>
					<li>Sunday<span>10am - 11pm</span></li>
				</ul>
			</aside>
			
		</div>
		<!-- END Widget Column 03 -->
	
	</div>
	<!-- END Widget Area -->
	
</footer>
<!-- END Site Footer -->

app/views/shared/_footer_two.html.erb
<div id="bottom-footer">
	<div class="grid-container">
	
		<!-- Footer Logo -->
		<div class="footer-logo grid-50 tablet-grid-100 mobile-grid-100">
			<a href="#"><img class="footer-logo-image" src="/assets/assets/footer-logo.png" alt="Footer Logo" /></a>
		</div>
	
		<!-- Footer Text -->
		<div class="footer-text grid-50 tablet-grid-100 mobile-grid-100">
			<p>Designed by <a href="http://themeforest.net/user/SubatomicThemes" target="_blank">Subatomic Themes</a> for <a href="http://themeforest.net" target="_blank">Themeforest</a>. All Rights Reserved.</p>
		</div>
	
	</div>
</div>

app/views/shared/_head_html.html.erb
<!-- START HEAD -->
<!-- START Meta -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
<meta name=”robots” content=”index”>
<meta name=”robots” content=”follow”>
<!-- END Meta -->

<title> Pizza Three Guys </title>
<meta name='description' content='Best food, Pizza in Washington, Pa'>

<!-- Google Fonts:
	 Ubuntu          - http://www.google.com/fonts/specimen/Ubuntu
	 Droid Serif     - http://www.google.com/fonts/specimen/Droid+Serif 
	 Aguafina Script - http://www.google.com/fonts/specimen/Aguafina+Script -->
<link href="http://fonts.googleapis.com/css?family=Ubuntu:400,700%7CDroid+Serif:400,400italic,700,700italic%7CAguafina+Script" rel="stylesheet" type="text/css">

<!-- START Stylesheets -->
<link rel="stylesheet" href="/assets/client/formalize.css" media="all">
<link rel="stylesheet" href="/assets/client/unsemantic-grid.css" media="all">
<link rel="stylesheet" href="/assets/client/font-awesome.min.css" media="all">
<link rel="stylesheet" href="/assets/client/animate.mod.min.css" media="all">
<link rel="stylesheet" href="/assets/client/tooltipster.css" media="all">
<link rel="stylesheet" href="/assets/client/jquery-ui.min.css" media="all">
<link rel="stylesheet" href="/assets/client/style.css" media="all">
<!-- END Stylesheets -->

<!-- START Javascripts -->
<script type="text/javascript" src="/assets/client/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="/assets/client/jquery-ui.min.js"></script>
<!-- END Javascripts -->


<%= csrf_meta_tags %>
<%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!-- END HEAD -->

app/views/shared/navbar/_nav_header.html.erb
<div class="grid-20 tablet-grid-50 mobile-grid-50">
	<a href="index.html">
	</a>
	<%= link_to "#{root_path}#hungry-top" do%>
		<img class="site-logo" src="/assets/assets/logo.png" alt="Site Logo" />
	<% end %>
</div>
<!-- END Site Logo -->

<!-- START Navigation -->
<div class="nav-container grid-80 tablet-grid-50 mobile-grid-50">

	<!-- Mobile Nav Icon (Hamburger) -->
	<div class="mobile-nav">
		<i class="fa fa-bars"></i>
	</div>

	<nav class="main-navigation" role="navigation">
		
		<!-- Mobile Menu Header -->
		<div class="mobile-header hide-on-desktop">
			<h2>Navigation</h2>
			<div class="mobile-close">
				<i class="fa fa-times"></i>
			</div>
		</div>
	
		<!-- Main Navigation -->
		<ul class="sf-menu">
			<li><%= link_to 'Home', "#{root_path}#hungry-top" %></li>
			<li><%= link_to 'Coupons', "#{root_path}#hungry-coupons" %></li>
			<li><%= link_to "Our Menu", "#{root_path}#hungry-menu"%>
				<ul>
					<li><%= link_to "Our Menu", menu_path %></li>
					<!-- <li><a href="template-menu-one-column.html">Single Column Layout</a></li> -->
					<!-- <li><a href="template-menu-three-columns.html">Three Column Layout</a></li> -->
				</ul>
			</li>
			<li>
				<%#= link_to "Our Blog", "#{root_path}#hungry-blog" %>
				<ul>
					<li><a href="template-blog-overview.html">Overview Page</a></li>
					<li><a href="template-blog-single-right-sidebar.html">Single Entry Page</a>
						<ul>
							<li><a href="template-blog-single-left-sidebar.html">Left Sidebar</a></li>
							<li><a href="template-blog-single-right-sidebar.html">Right Sidebar</a></li>
							<li><a href="template-blog-single-full-width.html">Full Width</a></li>
							<li><a href="template-blog-single-narrow.html">Narrow</a></li>
						</ul>
					</li>
				</ul>
			</li>
			<li><%= link_to "Contact Us", "#{root_path}#hungry-about-us" %></li>
			<li><%= link_to "Order Online", "#" %></li>
			<li><%= link_to "Catering", "#" %></li>

			<!-- <li><%#= link_to "The Gallery", "#{root_path}#hungry-gallery" %></li> -->
			<!-- <li><%#= link_to "Our Team", "#{root_path}#hungry-staff" %></li> -->
			<!-- <li><%#= link_to "Reservations", "#{root_path}#hungry-reservations" %></li> -->
		</ul>
		
	</nav>
</div>

app/views/shared/navbar/_navbar.html.erb
<header id="single-page-header">
	<div class="site-navbar">
		<div class="grid-container">
			<%= render 'shared/navbar/nav_header' %>
		</div>
	</div>
	
	<div class="single-page-header-content">
		<!-- START Slider Images -->
		<div class="cycle-slideshow"
			 data-cycle-swipe="true"
			 data-cycle-swipe-fx="fade"
			 data-cycle-fx="fade"
			 data-cycle-speed="1200"
			 data-cycle-timeout="16000">
			
			<!-- Images -->
			<img src="/assets/demo/slides/pizzathreeguys_pastas.jpg" alt="Slide Image 02" />
			<img src="/assets/demo/slides/pizzathreeguys_pizza.jpg" alt="Slide Image 01" />
			<img src="/assets/demo/slides/pizzathreeguys_wings.jpg" alt="Slide Image 02" />
			<img src="/assets/demo/slides/pizzathreeguys_salad.jpg" alt="Slide Image 03" />
			
			<!-- Prev/Next Buttons -->
			<div class="cycle-prev"><i class="fa fa-chevron-left"></i></div>
			<div class="cycle-next"><i class="fa fa-chevron-right"></i></div>
			
		</div>
		<!-- END Slider Images -->
	
		<!-- START Slider Texts -->
		<div class="single-page-header-text">
		
			<!-- Pre-slogan -->
			<!-- <div class="tilt-left">
				<h3 class="header-text-pre-slogan">Order Now!<em>&hellip;</em></h3>
			</div> -->	
		
			<!-- Slogan Rotator -->
			<div class="tlt">
				<ul class="header-texts">
					<li>We Serve Pastas</li>
					<li>We do online order!</li>
					<li>Check Out Specials!</li>
					<li>We do catering!</li>
				</ul>
			</div>
			
			<!-- Divider -->
			<div class="header-text-divider"></div>
			
		</div>
		<!-- END Slider Texts -->
	</div>
	
	<!-- Pre-slogan -->
	<!-- START Social Icons -->
	<div class="single-page-social-icons">
	<div class="tilt-left">
		<a href="">
			<h3 class="header-text-pre-slogan">Click To Order Now!<em>&hellip;</em></h3>
		</a>
	</div>
	<!-- 	<ul class="single-page-social-icons-list">
			<li><a href="#" class="header-social-icon-tooltip" title="Follow us on Facebook!"><i class="fa fa-facebook"></i></a></li>
			<li><a href="#" class="header-social-icon-tooltip" title="Find us in Twitter!"><i class="fa fa-twitter"></i></a></li>
			<li><a href="#" class="header-social-icon-tooltip" title="Pin us on Pinterest!"><i class="fa fa-pinterest"></i></a></li>
			<li><a href="#" class="header-social-icon-tooltip" title="See us on Vimeo!"><i class="fa fa-vimeo-square"></i></a></li>
			<li><a href="#" class="header-social-icon-tooltip" title="We're on OpenTable!"><i class="fa fa-cutlery"></i></a></li>
		</ul> -->
	</div>
	<!-- END Social Icons -->
	
</header>

app/views/shared/navbar/_navbar_menu.html.erb
<header id="subpage-header" class="alt-header">
	<div class="site-navbar">
		<div class="grid-container">
			<%= render 'shared/navbar/nav_header' %>
		</div>
	</div>
	
	<!-- START Subpage Intro -->
	<div class="grid-container">
		<div class="page-meta grid-100 tablet-grid-100 mobile-grid-100">
		
			<div class="wow fadeInUp" data-wow-duration="2s" data-wow-offset="250">
			
				<!-- Page Title -->
				<h1 class="page-title">The Menu</h1>
			
				<!-- START Breadcrumb Trail -->
				<div class="breadcrumb-trail-container tilt-left">
					<div class="breadcrumb-trail">
						<span class="trail-start"> <%= link_to "Home", "#{root_path}#hungry-top" %> </span>
						<span class="trail-end">Current Menu</span>
					</div>
				</div>
				<!-- END Breadcrumb Trail -->
				
			</div>
			
		</div>
	</div>
	<!-- END Subpage Intro -->
</header>